### ISSUE TITLE
change text color

### ISSUE THREAD

**Issue by pedroalencar1** [zhaouv/vscode-python-highlight-cell-splitter#1]
Hi there, 

thanks for the nice feature. However, can I change the text color? I tried changing on settings.json with no success

**Comment by zhaouv** [comment]
You can find the name of your current color theme in settings.json at workbench.colorTheme. For example `"workbench.colorTheme": "Default Light+"`.
And you change the name in you settings
```json
    "editor.tokenColorCustomizations": {
        "[Default Light+]": {
            "textMateRules": [
                {
                    "scope": "markup.heading.python.cell.splitter",
                    "settings": {
                        "fontStyle": "bold",
                        "foreground": "#40b903"
                    }
                }
            ]
        }
    },
```
Notice that the name in second line is changed.

**Comment by pedroalencar1** [comment]
Thanks! I had tried changing only the `"textMateRules"` colour but it wasn't working. Once I changed the colorTheme too it worked.

Cheers
